<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="Avalonia.Headless" Version="12.0.4" />
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="12.0.4" />
    <PackageReference Include="Avalonia.Skia" Version="12.0.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AvaScope.Protocol\AvaScope.Protocol.csproj" />
  </ItemGroup>

</Project>
